name: 'KenHa action demo'
description: 'A demo of Ken'
author: 'KenHa'
inputs:
  GITHUB_TOKEN:
    required: true
    description: 'github token'
  PullRequestNumber:
    required: true
    description: 'pr number'
outputs:
  pullRequestNumber:
    description: 'The number of pr'
runs:
  using: 'node12'
  main: 'dist/index.js'
